################################
# EC2 Instance ID
################################
output "instance_id" {
  description = "ID of the EC2 instance"
  value       = aws_instance.this.id
}

################################
# EC2 Public IP Address
################################
output "instance_public_ip" {
  description = "Public IP address of the EC2 instance"
  value       = aws_instance.this.public_ip
}

################################
# Directus Application URL
################################
output "directus_url" {
  description = "URL to access Directus application"
  value       = "http://${aws_instance.this.public_ip}:8055"
}

################################
# SSH Private Key (Sensitive)
################################
output "private_key" {
  description = "Private SSH key generated by Terraform"
  value       = tls_private_key.ssh_key.private_key_pem
  sensitive   = true
}
